DROP DATABASE IF EXISTS residentz;
CREATE DATABASE residentz;
USE residentz;

CREATE TABLE admin (
    A_ID INT PRIMARY KEY AUTO_INCREMENT,
    Email_ID VARCHAR(20) NOT NULL,
    Password INT(15) NOT NULL UNIQUE,
    Name VARCHAR(10) NOT NULL,
    DOB INT(8) NOT NULL,
    Mobile_No INT(10) NOT NULL UNIQUE,
    Gender VARCHAR(5) NOT NULL
);

CREATE TABLE user (
    E_ID INT PRIMARY KEY AUTO_INCREMENT,
    Email_id VARCHAR(15) NOT NULL,
    Password INT(7) NOT NULL UNIQUE,
    Name VARCHAR(10) NOT NULL,
    Mobile_No INT(10) NOT NULL UNIQUE,
    Gender VARCHAR(5) NOT NULL
);

CREATE TABLE event (
    P_ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(10) NOT NULL,
    Email_id VARCHAR(15) NOT NULL,
    Mobile_No INT(10) NOT NULL UNIQUE
);

CREATE TABLE maintenance (
    M_ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(10) NOT NULL,
    Email_id VARCHAR(15) NOT NULL,
    Mobile_No INT(10) NOT NULL UNIQUE,
    Password INT(7) NOT NULL UNIQUE
);
